# Harjas Bajwa
# CodeClause Internship 
# Project 1-FakeNewsDetection

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.svm import LinearSVC

In [2]:
data=pd.read_csv("/Users/harjasbajwa/fakenews/data/fake_or_real_news.csv")

In [3]:
data['fake']=data['label'].apply(lambda x: 0 if x == "REAL" else 1)

In [4]:
data=data.drop("label",axis=1)

In [5]:
X, y=data['text'], data['fake']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [7]:
vectorizer = TfidfVectorizer(stop_words="english", max_df=0.7)
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

In [8]:
clf = LinearSVC()
clf.fit(X_train_vectorized, y_train)

LinearSVC()

In [9]:
clf.score(X_test_vectorized, y_test)

0.9337016574585635

In [10]:
len(y_test) * 0.9455

1197.9485

In [11]:
len(y_test)

1267

In [12]:
#used for storing a news article from dataset
with open("mytext.txt", "w", encoding="utf-8") as f:
    f.write(X_test.iloc[10])

In [13]:
#loading article
with open("mytext.txt", "r", encoding="utf-8") as f:
    text=f.read()

In [14]:
text2="India won 2015 mens cricket world cup" #fake
text1="Osama Bin Laden is dead" #real
vectorized_text = vectorizer.transform([text])
vec2 = vectorizer.transform([text2])
vec3 = vectorizer.transform([text1])

In [15]:

clf.predict(vec2)

array([1])

In [16]:
clf.predict(vectorized_text)

array([0])

In [17]:
clf.predict(vec3)

array([0])

In [18]:
 y_test.iloc[10]

0